version: "3.7"

services:
  db:

    image: postgres:15
    container_name: db
    command: -p 5432
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - custom


  web:

    build:
      dockerfile: Dockerfile
    container_name: "web"
    ports:
      - "8000:8000"
    networks:
      - custom
    depends_on:
      - db
    env_file:
      - .env_dev

networks:
  custom:
    driver: bridge
